const nftStakingAddress = "0x2CE5D68c80f0499274b15134C9F4B17f411A8136"
const nftStakingAbi = [
    {
        "inputs":[
            
        ],
        "stateMutability":"nonpayable",
        "type":"constructor"
    },
    {
        "anonymous":false,
        "inputs":[
            {
                "indexed":true,
                "internalType":"address",
                "name":"previousOwner",
                "type":"address"
            },
            {
                "indexed":true,
                "internalType":"address",
                "name":"newOwner",
                "type":"address"
            }
        ],
        "name":"OwnershipTransferred",
        "type":"event"
    },
    {
        "inputs":[
            {
                "internalType":"uint256",
                "name":"stakingItemId",
                "type":"uint256"
            }
        ],
        "name":"getStakingItemAccount",
        "outputs":[
            {
                "internalType":"address",
                "name":"",
                "type":"address"
            }
        ],
        "stateMutability":"view",
        "type":"function"
    },
    {
        "inputs":[
            {
                "internalType":"uint256",
                "name":"stakingItemId",
                "type":"uint256"
            }
        ],
        "name":"getStakingItemAmount",
        "outputs":[
            {
                "internalType":"uint256",
                "name":"",
                "type":"uint256"
            }
        ],
        "stateMutability":"view",
        "type":"function"
    },
    {
        "inputs":[
            {
                "internalType":"uint256",
                "name":"stakingItemId",
                "type":"uint256"
            }
        ],
        "name":"getStakingItemIsClaimed",
        "outputs":[
            {
                "internalType":"bool",
                "name":"",
                "type":"bool"
            }
        ],
        "stateMutability":"view",
        "type":"function"
    },
    {
        "inputs":[
            {
                "internalType":"uint256",
                "name":"stakingItemId",
                "type":"uint256"
            }
        ],
        "name":"getStakingItemIsWithdrawnWithoutMinting",
        "outputs":[
            {
                "internalType":"bool",
                "name":"",
                "type":"bool"
            }
        ],
        "stateMutability":"view",
        "type":"function"
    },
    {
        "inputs":[
            {
                "internalType":"uint256",
                "name":"stakingItemId",
                "type":"uint256"
            }
        ],
        "name":"getStakingItemNftContractAddress",
        "outputs":[
            {
                "internalType":"address",
                "name":"",
                "type":"address"
            }
        ],
        "stateMutability":"view",
        "type":"function"
    },
    {
        "inputs":[
            {
                "internalType":"uint256",
                "name":"stakingItemId",
                "type":"uint256"
            }
        ],
        "name":"getStakingItemStartTime",
        "outputs":[
            {
                "internalType":"uint256",
                "name":"",
                "type":"uint256"
            }
        ],
        "stateMutability":"view",
        "type":"function"
    },
    {
        "inputs":[
            {
                "internalType":"address",
                "name":"account",
                "type":"address"
            }
        ],
        "name":"getStakingItems",
        "outputs":[
            {
                "components":[
                    {
                        "internalType":"address",
                        "name":"nftContractAddress",
                        "type":"address"
                    },
                    {
                        "internalType":"address",
                        "name":"account",
                        "type":"address"
                    },
                    {
                        "internalType":"uint256",
                        "name":"amount",
                        "type":"uint256"
                    },
                    {
                        "internalType":"uint256",
                        "name":"startTime",
                        "type":"uint256"
                    },
                    {
                        "internalType":"bool",
                        "name":"isWithdrawnWithoutMinting",
                        "type":"bool"
                    },
                    {
                        "internalType":"bool",
                        "name":"isClaimed",
                        "type":"bool"
                    }
                ],
                "internalType":"struct NFTStaking.StakingItem[]",
                "name":"",
                "type":"tuple[]"
            }
        ],
        "stateMutability":"view",
        "type":"function"
    },
    {
        "inputs":[
            
        ],
        "name":"getStakingTokenAddress",
        "outputs":[
            {
                "internalType":"address",
                "name":"",
                "type":"address"
            }
        ],
        "stateMutability":"view",
        "type":"function"
    },
    {
        "inputs":[
            
        ],
        "name":"owner",
        "outputs":[
            {
                "internalType":"address",
                "name":"",
                "type":"address"
            }
        ],
        "stateMutability":"view",
        "type":"function"
    },
    {
        "inputs":[
            
        ],
        "name":"renounceOwnership",
        "outputs":[
            
        ],
        "stateMutability":"nonpayable",
        "type":"function"
    },
    {
        "inputs":[
            {
                "internalType":"address",
                "name":"collection",
                "type":"address"
            },
            {
                "internalType":"bool",
                "name":"status",
                "type":"bool"
            }
        ],
        "name":"setCollection",
        "outputs":[
            
        ],
        "stateMutability":"nonpayable",
        "type":"function"
    },
    {
        "inputs":[
            {
                "internalType":"uint256",
                "name":"_idToStakingItem",
                "type":"uint256"
            }
        ],
        "name":"setStakingItemAsClaimed",
        "outputs":[
            
        ],
        "stateMutability":"nonpayable",
        "type":"function"
    },
    {
        "inputs":[
            {
                "internalType":"address payable",
                "name":"_stakingTokenAddress",
                "type":"address"
            }
        ],
        "name":"setStakingTokenAddress",
        "outputs":[
            
        ],
        "stateMutability":"nonpayable",
        "type":"function"
    },
    {
        "inputs":[
            {
                "internalType":"address",
                "name":"_nftContractAddress",
                "type":"address"
            },
            {
                "internalType":"uint256",
                "name":"amount",
                "type":"uint256"
            }
        ],
        "name":"stake",
        "outputs":[
            
        ],
        "stateMutability":"nonpayable",
        "type":"function"
    },
    {
        "inputs":[
            {
                "internalType":"address",
                "name":"newOwner",
                "type":"address"
            }
        ],
        "name":"transferOwnership",
        "outputs":[
            
        ],
        "stateMutability":"nonpayable",
        "type":"function"
    },
    {
        "inputs":[
            {
                "internalType":"uint256",
                "name":"_idToStakingItem",
                "type":"uint256"
            }
        ],
        "name":"unstake",
        "outputs":[
            
        ],
        "stateMutability":"nonpayable",
        "type":"function"
    }
]

export { nftStakingAbi, nftStakingAddress }